/**
 * 报告导出工具库
 * 提供复制到剪贴板和导出 PDF 的功能
 */

interface Insight {
  title: string;
  severity: string;
  category: string;
  description: string;
  opportunity: string;
  quote: string | null;
  quoteAuthor?: string;
  quoteLink?: string;
}

interface AnalysisData {
  summary: string;
  frustrationScore: number;
  insights: Insight[];
}

interface ReportData {
  data: AnalysisData;
  query?: string;
  timestamp?: string;
}

/**
 * 生成 JSON 格式的报告数据
 */
export function generateReportJSON(reportData: ReportData): string {
  const { data, query, timestamp } = reportData;
  
  const report = {
    metadata: {
      title: 'Pain Point Analysis Report',
      query: query || 'N/A',
      generatedAt: timestamp || new Date().toISOString(),
      frustrationScore: data.frustrationScore,
    },
    summary: data.summary,
    insights: data.insights.map((insight, index) => ({
      rank: index + 1,
      title: insight.title,
      severity: insight.severity,
      category: insight.category,
      description: insight.description,
      opportunity: insight.opportunity,
      userFeedback: insight.quote ? {
        quote: insight.quote,
        author: insight.quoteAuthor || 'Reddit User',
        source: insight.quoteLink || null,
      } : null,
    })),
  };

  return JSON.stringify(report, null, 2);
}

/**
 * 生成可读的文本格式报告
 */
export function generateReadableReport(reportData: ReportData): string {
  const { data, query, timestamp } = reportData;
  
  const lines = [
    '═══════════════════════════════════════════════',
    '🔍 PAIN POINT ANALYSIS REPORT',
    '═══════════════════════════════════════════════',
    '',
    '📋 REPORT DETAILS',
    '─────────────────────────────────────────────',
    `Search Query: ${query || 'N/A'}`,
    `Generated: ${timestamp || new Date().toLocaleString()}`,
    `Frustration Score: ${data.frustrationScore}/100 ${getScoreEmoji(data.frustrationScore)}`,
    '',
    '📊 EXECUTIVE SUMMARY',
    '─────────────────────────────────────────────',
    data.summary,
    '',
    '',
    `🎯 TOP PAIN POINTS (${data.insights.length} identified)`,
    '═══════════════════════════════════════════════',
    '',
  ];

  data.insights.forEach((insight, index) => {
    lines.push(`${index + 1}. ${insight.title}`);
    lines.push('─'.repeat(50));
    lines.push('');
    lines.push(`   🔥 Severity: ${insight.severity}`);
    lines.push(`   📁 Category: ${insight.category}`);
    lines.push('');
    lines.push(`   📝 Description:`);
    lines.push(`   ${insight.description}`);
    lines.push('');
    lines.push(`   💡 Opportunity:`);
    lines.push(`   ${insight.opportunity}`);
    
    if (insight.quote) {
      lines.push('');
      lines.push(`   💬 User Quote:`);
      lines.push(`   "${insight.quote}"`);
      if (insight.quoteAuthor) {
        lines.push(`   — ${insight.quoteAuthor}`);
      }
      if (insight.quoteLink) {
        lines.push(`   🔗 Source: ${insight.quoteLink}`);
      }
    }
    
    lines.push('');
    lines.push('');
  });

  lines.push('═══════════════════════════════════════════════');
  lines.push('Generated by AI Pain Point Analyzer');
  lines.push('═══════════════════════════════════════════════');

  return lines.join('\n');
}

/**
 * 根据分数返回表情符号
 */
function getScoreEmoji(score: number): string {
  if (score >= 80) return '🔴 Very High';
  if (score >= 60) return '🟠 High';
  if (score >= 40) return '🟡 Medium';
  return '🟢 Low';
}

/**
 * 复制报告到剪贴板
 * @param reportData 报告数据
 * @param format 格式：'readable'（可读文本）或 'json'
 * @returns Promise<boolean> 是否成功
 */
export async function copyReportToClipboard(
  reportData: ReportData,
  format: 'readable' | 'json' = 'readable'
): Promise<boolean> {
  try {
    const content = format === 'json' 
      ? generateReportJSON(reportData)
      : generateReadableReport(reportData);

    await navigator.clipboard.writeText(content);
    return true;
  } catch (error) {
    console.error('[ReportExport] Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * 导出报告为 PDF（直接下载）
 * 步骤：
 * 1. 点击 "Export to PDF"
 * 2. 直接打开文件保存对话框
 * 3. 用户选择存放目录地址
 * 4. 用户点击"保存"按钮
 * 5. PDF 文件下载完成！
 */
export async function exportReportToPDF(reportData: ReportData): Promise<void> {
  const { data, query } = reportData;
  
  // 动态导入 jsPDF 和 html2canvas
  const { default: jsPDF } = await import('jspdf');
  const html2canvas = (await import('html2canvas')).default;
  
  // 生成文件名
  const filename = `pain-point-report-${query?.replace(/\s+/g, '-').toLowerCase() || 'analysis'}.pdf`;
  
  // 创建临时容器
  const container = document.createElement('div');
  container.style.position = 'fixed';
  container.style.left = '-9999px';
  container.style.top = '0';
  container.style.width = '210mm'; // A4 宽度
  container.style.padding = '20mm';
  container.style.backgroundColor = 'white';
  container.innerHTML = generatePrintableHTML(reportData);
  document.body.appendChild(container);
  
  try {
    // 将 HTML 转换为 Canvas
    const canvas = await html2canvas(container, {
      scale: 2, // 提高清晰度
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });
    
    // 创建 PDF
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
    
    const imgWidth = 210; // A4 宽度（mm）
    const pageHeight = 297; // A4 高度（mm）
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;
    
    const imgData = canvas.toDataURL('image/png');
    
    // 添加第一页
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
    
    // 如果内容超过一页，添加更多页面
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }
    
    // 触发下载 - 直接弹出保存对话框
    pdf.save(filename);
    
  } finally {
    // 清理临时容器
    document.body.removeChild(container);
  }
}

/**
 * 生成可打印的 HTML（用于 PDF 生成）
 */
function generatePrintableHTML(reportData: ReportData): string {
  const { data, query, timestamp } = reportData;
  
  return `
<style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    line-height: 1.6;
    color: #1f2937;
    font-size: 11pt;
    background: white;
    padding: 20px;
  }
  
  .header {
    text-align: center;
    margin-bottom: 30px;
    padding-bottom: 20px;
    border-bottom: 3px solid #3b82f6;
  }
  
  h1 {
    font-size: 28pt;
    font-weight: bold;
    margin-bottom: 10px;
    color: #111827;
  }
  
  .subtitle {
    font-size: 12pt;
    color: #6b7280;
    margin-top: 5px;
  }
  
  .metadata {
    background: #f3f4f6;
    padding: 15px;
    border-radius: 8px;
    margin-bottom: 25px;
    font-size: 10pt;
  }
  
  .metadata-row {
    display: flex;
    justify-content: space-between;
    margin: 5px 0;
    align-items: center;
  }
  
  .metadata-label {
    font-weight: 600;
    color: #6b7280;
  }
  
  .score-badge {
    display: inline-block;
    background: #fef2f2;
    color: #dc2626;
    padding: 8px 20px;
    border-radius: 25px;
    font-weight: 700;
    font-size: 16pt;
    border: 2px solid #fecaca;
  }
  
  h2 {
    font-size: 18pt;
    font-weight: 600;
    margin-top: 30px;
    margin-bottom: 15px;
    color: #111827;
    border-bottom: 2px solid #e5e7eb;
    padding-bottom: 10px;
  }
  
  .summary {
    background: #f9fafb;
    padding: 18px;
    border-radius: 8px;
    margin-bottom: 30px;
    border-left: 5px solid #3b82f6;
    font-size: 11pt;
    line-height: 1.8;
  }
  
  .insights-count {
    color: #6b7280;
    font-size: 12pt;
    margin-bottom: 20px;
    font-weight: 500;
  }
  
  .insight-card {
    background: #ffffff;
    border: 2px solid #e5e7eb;
    border-radius: 10px;
    padding: 20px;
    margin-bottom: 20px;
  }
  
  .insight-header {
    margin-bottom: 15px;
  }
  
  .insight-title {
    font-size: 14pt;
    font-weight: 700;
    color: #111827;
    margin-bottom: 10px;
    display: flex;
    align-items: center;
    gap: 10px;
  }
  
  .insight-rank {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
    color: white;
    min-width: 32px;
    height: 32px;
    border-radius: 50%;
    font-weight: bold;
    font-size: 12pt;
    flex-shrink: 0;
  }
  
  .badges {
    display: flex;
    gap: 10px;
    margin-bottom: 15px;
    flex-wrap: wrap;
  }
  
  .badge {
    display: inline-block;
    padding: 6px 14px;
    border-radius: 20px;
    font-size: 9pt;
    font-weight: 600;
    border: 1px solid;
  }
  
  .badge-high {
    background: #fee2e2;
    color: #991b1b;
    border-color: #fecaca;
  }
  
  .badge-medium {
    background: #fed7aa;
    color: #9a3412;
    border-color: #fdba74;
  }
  
  .badge-low {
    background: #fef3c7;
    color: #92400e;
    border-color: #fde68a;
  }
  
  .badge-category {
    background: #dbeafe;
    color: #1e40af;
    border-color: #bfdbfe;
  }
  
  .section {
    margin-bottom: 15px;
  }
  
  .section-label {
    font-weight: 700;
    color: #374151;
    font-size: 10pt;
    margin-bottom: 8px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  
  .description {
    color: #4b5563;
    font-size: 10.5pt;
    line-height: 1.7;
  }
  
  .opportunity-box {
    background: linear-gradient(135deg, #ecfeff 0%, #dbeafe 100%);
    border: 2px solid #67e8f9;
    border-radius: 8px;
    padding: 15px;
    margin-top: 15px;
  }
  
  .opportunity-label {
    font-weight: 700;
    color: #0e7490;
    font-size: 10pt;
    margin-bottom: 8px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  
  .opportunity-text {
    color: #164e63;
    font-size: 10.5pt;
    line-height: 1.7;
  }
  
  .quote-box {
    border-left: 4px solid #d1d5db;
    background: #f9fafb;
    padding: 12px 15px;
    margin-top: 15px;
    border-radius: 4px;
  }
  
  .quote-text {
    font-style: italic;
    color: #6b7280;
    font-size: 10pt;
    line-height: 1.6;
    margin-bottom: 8px;
  }
  
  .quote-author {
    font-size: 9pt;
    font-style: normal;
    font-weight: 600;
    color: #9ca3af;
  }
  
  .footer {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 2px solid #e5e7eb;
    text-align: center;
    font-size: 9pt;
    color: #9ca3af;
  }
  
  .footer-logo {
    font-weight: 700;
    color: #3b82f6;
    font-size: 10pt;
    margin-bottom: 5px;
  }
</style>

<div class="container">
  <div class="header">
    <h1>🔍 Pain Point Analysis Report</h1>
    <div class="subtitle">Comprehensive User Pain Point Discovery & Analysis</div>
  </div>
  
  <div class="metadata">
    <div class="metadata-row">
      <span><span class="metadata-label">Search Query:</span> ${query || 'N/A'}</span>
      <span><span class="metadata-label">Generated:</span> ${timestamp || new Date().toLocaleString()}</span>
    </div>
    <div class="metadata-row" style="margin-top: 12px;">
      <span class="metadata-label">Frustration Score:</span>
      <span class="score-badge">${data.frustrationScore} / 100</span>
    </div>
  </div>
  
  <h2>📊 Executive Summary</h2>
  <div class="summary">
    ${data.summary}
  </div>
  
  <h2>🎯 Detailed Pain Point Analysis</h2>
  <div class="insights-count">Total Pain Points Identified: <strong>${data.insights.length}</strong></div>
  
  ${data.insights.map((insight, index) => `
    <div class="insight-card">
      <div class="insight-header">
        <div class="insight-title">
          <span class="insight-rank">${index + 1}</span>
          <span>${insight.title}</span>
        </div>
        
        <div class="badges">
          <span class="badge ${getSeverityClass(insight.severity)}">🔥 ${insight.severity}</span>
          <span class="badge badge-category">📁 ${insight.category}</span>
        </div>
      </div>
      
      <div class="section">
        <div class="section-label">Problem Description</div>
        <div class="description">${insight.description}</div>
      </div>
      
      <div class="opportunity-box">
        <div class="opportunity-label">💡 Business Opportunity</div>
        <div class="opportunity-text">${insight.opportunity}</div>
      </div>
      
      ${insight.quote ? `
        <div class="quote-box">
          <div class="quote-text">"${insight.quote}"</div>
          <div class="quote-author">— ${insight.quoteAuthor || 'Anonymous User'}</div>
        </div>
      ` : ''}
    </div>
  `).join('')}
  
  <div class="footer">
    <div class="footer-logo">AI Pain Point Analyzer</div>
    <div>© ${new Date().getFullYear()} All Rights Reserved</div>
    <div style="margin-top: 5px; font-size: 8pt; color: #d1d5db;">
      This report is generated automatically using AI analysis
    </div>
  </div>
</div>
  `;
}

/**
 * 辅助函数：获取严重性对应的 CSS 类
 */
function getSeverityClass(severity: string): string {
  if (severity.toLowerCase().includes('high') || severity.includes('高')) {
    return 'badge-high';
  }
  if (severity.toLowerCase().includes('medium') || severity.includes('中')) {
    return 'badge-medium';
  }
  return 'badge-low';
}
